### PR TITLE
[Don't merge] Please kick Travis CI again!

### PR DESCRIPTION
**Pull request by y-yu**
- Travis CI on the `master` branch is failing 😢 but It doesn't seem to be broken
- So I try out to run the CI again using empty commit 7b4356bdcec96fa5f13ecc7d8fa660b46531b2d4
    - This PR is only containing the empty commit. That's the why this PR must NOT be merged
    - I intend this PR is an evidence that shows `master` branch actually has no problem
- Finally https://travis-ci.org/github/y-yu/AppIcon/builds/679634470 succeed! 🎉 
- Please run the Travis CI job for `master` branch again 🙏 and close this PR

### CODE REVIEW

**Comment by y-yu** [comment]
But Travis CI connection problem occurred..... (see also https://github.com/gfngfn/SATySFi/issues/224)
It would be better to move [tarvis-ci.com](https://travis-ci.com) instead of `travis-ci.org` or an other CI service.

**Comment by Nonchalant** [comment]
@y-yu 
Thank you for sharing your knowledge.
I will migrate travic-ci.com from travis-ci.org 🍀

**Comment by Nonchalant** [comment]
I migrated, thanks!
https://github.com/Nonchalant/AppIcon/pull/63

**Comment by y-yu** [comment]
Thanks! 👍

**Pull request closed without merging**
